# Generated by Django 2.0.4 on 2018-04-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imageFileName',
            field=models.CharField(blank=True, help_text='Enter logo file name', max_length=200, null=True),
        ),
    ]
