# Generated by Django 2.0.4 on 2018-04-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_auto_20180428_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imageFileName',
            field=models.CharField(help_text='Enter logo file name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='soundFileName',
            field=models.CharField(blank=True, help_text='Enter sound file name', max_length=200, null=True),
        ),
    ]
