# Generated by Django 2.0.4 on 2018-04-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_exhibitneighbors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExhibitNeighbors',
            new_name='ExhibitNeighbor',
        ),
    ]
