# Generated by Django 2.0.4 on 2018-04-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0009_auto_20180428_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitneighbor',
            name='direction',
            field=models.CharField(choices=[('n', 'North'), ('s', 'South'), ('e', 'East'), ('w', 'West'), ('nw', 'Northwest'), ('sw', 'Southwest'), ('ne', 'Northeast'), ('se', 'Southeast')], help_text='Enter cardinal travel direction.', max_length=2),
        ),
        migrations.AlterField(
            model_name='exhibitneighbor',
            name='fromExhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromExhibit', to='zoo.Exhibit'),
        ),
    ]
